### ISSUE TITLE
Docker as a Distribution Dependency?

### ISSUE THREAD

**Issue by storrgie** [wireapp/wire-server#68]
It's a bit hard to ascertain the intent for _release_ from the existing code-base, but I wanted to make the inquiry about it:
 
> Is Docker going to be intended to be the primary distribution mechanism?

This is highly preferential, but it would be really great to be able to consume the services as a bundle or as separately built components in their built form as just an archive (e.g. tar.gz, xz), so that downstream distributions can work on packaging it appropriately.

Docker necessitates a pretty heavy dependency on potential wire-server operators. It makes life easier for those who are already using the docker ecosystem, but potentially much more convoluted for all other deployments. Secondarily it puts the packaging behind a layer of abstraction that makes for more difficulty when people want to package downstream.

**Comment by jschaul** [comment]
Hi @storrgie,

Thanks for your interest in wire-server. 

As [mentioned](https://github.com/wireapp/wire-server#roadmap), we are planning to provide information on how to build and run wire-server - this will still take some time, mainly because wire-server depends on a range of external services (as can be seen in the `External` part of the [deployment diagram](https://raw.githubusercontent.com/wireapp/wire-server/develop/doc/arch/wire-arch-2.png)). 

>  it would be really great to be able to consume the services as a bundle or as separately built components in their built form as just an archive (e.g. tar.gz, xz), so that downstream distributions can work on packaging it appropriately.

Providing built components as an archive makes little sense, as executables are dynamically linked thus dependent on the specific platform, architecture, and concrete versions of e.g. glibc and openssl. Therefore code needs to be compiled in the same environment that it is run in. 

> Is Docker going to be intended to be the primary distribution mechanism?

The primary distribution mechanism will be source code. We *might* also upload some form of container images.

**Comment by storrgie** [comment]
@jschaul your last statement:

> The primary distribution mechanism will be source code. We might also upload some form of container images.

Is what I was looking for. I'd much prefer this be released in a fashion that allows for Linux distributions to maintain downstream packages. Sounds like this is what you're planning to do.
