### ISSUE TITLE
Finnish users have issues receiving SMS verification codes

### ISSUE THREAD

**Issue by Mikaela** [wireapp/wire-server#776]
Possibly related to https://github.com/wireapp/wire-server/issues/504 (Finland is +358)

I have three family members/friends who registered to Wire recently, two of them are using iOS, one Android tablet. When they initially attempted to register (three weeks ago, two weeks ago and today), they received error messages and didn't receive the SMS code, but adding the number afterwards worked. However a friend who registered today had to try entering the code three times before it was accepted (after registering by email).

Are you aware of any long term problem affecting Finnish phone numbers?

I tried to send a message through [new support request](https://support.wire.com/hc/en-us/requests/new), but it didn't load the actual form regardless of µMatrix being disabled.

![Screenshot_2019-06-11 Submit a request – Wire – Support](https://user-images.githubusercontent.com/831184/59257844-45d8e900-8c26-11e9-85fe-25ac61166794.png)

**Comment by jschaul** [comment]
Hi @Mikaela 

About the phone number issue: Thanks for reporting this. Yes indeed, we had blocked phone numbers starting with `+358 4` due to repeated abuse of our API using these phone numbers. These phone numbers are now unblocked again, and SMS codes should arrive again (though we may have to block certain phone number ranges in the future again).

About support tickets: I'm not sure what the problem is here.

**Comment by Mikaela** [comment]
Thanks for the fast response. Could the clients give more clear error about phone number rannge being blocked and suggest using email registration instead (and adding number afterwards in the settings)? Currently it seems like something is wrong with Wire, I have used multiple phone number based services and I have never before encountered number range being blocked and at first I thought it was just a temporary issue.

What kind of abuse has it been? I don't know if you know, but when you attempt to register to Wire and give a password that the client doesn't accept (due to lack of special character), the verification code is still sent (at least by email), so I saw my famly members receiving 5 verification codes by email before successful registration. I am wondering if the abuse has been similar and entirely accidental.

`+358 4` is one of the mobile area codes of Telia Finland according to [Traficom's list](https://www.traficom.fi/en/communications/broadband-and-telephone/mobile-network-area-codes), I don't know how popular it is, but I think all of my close family is on that range even if everyone has since transferred their numbers to other operators.

**Comment by tiago-loureiro** [comment]
Hi @Mikaela - thank you for following up on this!

>  Could the clients give more clear error about phone number rannge being blocked and suggest using email registration instead (and adding number afterwards in the settings)? 

Yes, we do send out proper response codes from the backend side of things, we will work on giving users a more detailed explanation as to what is going on the clients.

> What kind of abuse has it been? I don't know if you know, but when you attempt to register to Wire and give a password that the client doesn't accept (due to lack of special character), the verification code is still sent (at least by email), so I saw my family members receiving 5 verification codes by email before successful registration. I am wondering if the abuse has been similar and entirely accidental.

Yes, I believe you are talking about: https://github.com/wireapp/wire-android/pull/2122 which got merged to develop just yesterday.

As mentioned by @jschaul we suffered some abuse from that range although we may have been a tad too aggressive and blocked a too wide range.

If all has been cleared now, could you please close this issue? I will open respective issues so that clients can display better errors messages.

**Comment by Mikaela** [comment]
Thank you
