### ISSUE TITLE
wher is wire admin panel

### ISSUE THREAD

**Issue by Nemra1** [wireapp/wire-server#78]
i want start to work with wire platform but i need to know whers wire admin panel after setup wire server?

**Comment by Evoludo** [comment]
Hi @Nemra1,

Thanks for your interest! We don't currently have an admin panel for use with the services in this repo. We're currently working on on improved tooling so that you can run your own wire server in future, but we're not quite there yet. Keep an eye on this repo for updates!

Andrew,
Backend Team, Wire
