### ISSUE TITLE
Error: Push token of unknown application: 'test', while hitting /push/token.

### ISSUE THREAD

**Issue by R4m4n** [wireapp/wire-server#837]
While hitting the API "POST /push/tokens", with data:

```
{
    "app" : "test",
    "client" :"ClientID",
    "token": "<APNS_TOKEN>",
    "transport" : "APNS_VOIP_SANDBOX"
}
```

an error is being thrown:
`Push token of unknown application: 'test'`
What should be the value of the appName while storing the push token API?

**Comment by jschaul** [comment]
There is no easy way for you to make use of push notifications at the moment. 

To get this working, the following is needed:

* an AWS account is needed
* a google and apple account is needed
* mobile apps need to be compiled and signed with different keys, and put into the play/app store (this isn't really possible for you to do easily due to licences)
* You need to create SNS endpoints and database entries in gundeck's cassandra manually. Only then can you start posting to `/push/tokens`.

If you need support on this and/or would like to collaborate, please contact us https://wire.com/en/contact/enterprise-requests/

Does this answer your question @R4m4n ?

**Comment by R4m4n** [comment]
Thanks for the answer @jschaul, 
I've already solved this issue. The issue was with the app name in the SNS console.
In the file Arn.hs:

`let name = toText e <> "-" <> appNameText n`

appName was being used as "arn in yaml" + "-" + "'app' key in the request".

I just set the proper "Application platform name" and "test" after "-" on the SNS and then sent the "app" value as "test".
Now everything's working fine.
