### ISSUE TITLE
Getting 404 for "/password-reset".

### ISSUE THREAD

**Issue by R4m4n** [wireapp/wire-server#860]
While hitting the reset password API from the swagger:
POST `http://example.com/password-reset`

Getting 404 Not Found error.

**Comment by R4m4n** [comment]
@tiago-loureiro, any idea about this issue, I'm not able to reset my password from the accounts app and is showing 404 when hitting from the swagger or postman.

**Comment by tiago-loureiro** [comment]
Hello @R4m4n 
`example.com`, as the name indicates, is just a placeholder. You will need to replace that with your server's DNS name.

**Comment by R4m4n** [comment]
@tiago-loureiro,
I used `example.com` as a placeholder, I'm using a proper domain name, and all other APIs are working fine except this one.

**Comment by jschaul** [comment]
Hi @R4m4n , thanks for raising the issue. This is indeed a bug due to the nginx configuration you're using (you seem to be using the one from https://github.com/wireapp/wire-server/tree/develop/deploy/services-demo/conf/nginz) not being up-to-date. If you install wire-server on top of kubernetes, as detailed [here](https://docs.wire.com) using the nginx configuration from [here](https://github.com/wireapp/wire-server-deploy/blob/develop/charts/nginz/values.yaml) you should not have that problem.

As a stop-gap measure, you can add

```nginx
    location /password-reset {
      include common_response_no_zauth.conf;
      proxy_pass http://brig;
    }
```

to the nginx configuration. A Pull request is welcome (there seem to be other routes missing, too).

**Comment by R4m4n** [comment]
Thanks a lot, @jschaul,
It's working now, quick question,
Which one should I use to deploy and seem it work like production while making some changes in the code too?
"https://github.com/wireapp/wire-server/"
OR
"https://github.com/wireapp/wire-server-deploy/"

**Comment by jschaul** [comment]
As written in the README, the docker-compose "installation" provided in https://github.com/wireapp/wire-server/ is for demo-purposes only, to try things on your laptop.

For a more serious deployment, please use the code on https://github.com/wireapp/wire-server-deploy and refer to documentation (work-in-progress, expect updates in the coming days/weeks, not done yet) on https://docs.wire.com

**Comment by R4m4n** [comment]
Thanks a lot, @jschaul, really appreciate it.
