### ISSUE TITLE
about user status

### ISSUE THREAD

**Issue by limengyu1990** [wireapp/wire-server#918]
I want to know how to better determine the online status of the current user? For example, when all the users' devices are offline, the user is offline. If any device is online, the user is considered to be online.

**Comment by jschaul** [comment]
Do you define "online" as "can receive a message now"?

On Wire, users are assumed to be always online. The reason is that people with iOS or Android devices rely on native push notifications to receive messages. As such, the server does not know if a person is "offline" in the sense of "push notifications cannot be delivered".

Wire makes use of two things: 1) websocket connections 2) native push notifications on iOS and Android clients. The server knows for which user there is an active websocket connection established, however this information can't be used as a way to distinguish "online" from "offline" users like in the messaging world from the past decade.

Does this answer your question?

**Comment by limengyu1990** [comment]
Thank you for your answer, I understand.
we currently define: As long as there is an active websocket connection to the server, the current user is considered to be in an `online` state.

my current solution is: In the `await` method, set the user status to`online`, in the `colse` method, handle the disconnection event and set the user status to` offline`.
